# Application specific bindings for random apps and shit


# FILE MANAGER
bind=SUPER+SHIFT,RETURN,spawn,thunar
bind=SUPER,N,spawn,thunar

# Browser
bind=SUPER,W,spawn,firefox
bind=SUPER,B,spawn,firefox

# Email client
bind=SUPER,M,spawn,thunderbird

# BTOP
bind=CTRL+SHIFT,Escape,spawn,ghostty -e btop