# Application specific bindings for random apps and shit


# FILE MANAGER
bind=SUPER,N,spawn,thunar

# Browser
bind=SUPER,W,spawn,firefox

# Email client
bind=SUPER,M,spawn,thunderbird

# BTOP
bind=CTRL+SHIFT,Escape,spawn,ghostty -e btop

# Volume Control
bind=SUPER+SHIFT,V,spawn,pavucontrol

# Screenshot
bind=NONE,print,spawn,hyprshot -m region --clipboard-only