# Application specific bindings for random apps and shit

# KDE connect ---> replace with valent for gtk4
exec-once=kdeconnectd && sleep 3 && kdeconnect-indicator
bind=Super+Shift,K,spawn,kdeconnect-app

# FILE MANAGER
bind=SUPER,N,spawn,thunar
exec-once=thunar --daemon # never kill the thunar process allowing for the file manager to open faster

# Browser
bind=SUPER,W,spawn,vivaldi
#bind=SUPER,W,spawn,firefox #--> replaced with vivaldi for efficiency

# Email client
bind=SUPER,M,spawn,thunderbird

# BTOP
bind=CTRL+SHIFT,Escape,spawn,ghostty -e btop

# Volume Control
bind=SUPER+SHIFT,V,spawn,pavucontrol

# Screenshot
bind=NONE,print,spawn,hyprshot -m region --clipboard-only
