# More option see https://github.com/DreamMaoMao/mango/wiki/


source=~/.config/mango/inputs.conf
source=~/.config/mango/keybinds.conf
source=~/.config/mango/monitor.conf
source=~/.config/mango/noctalia.conf
source=~/.config/mango/theming.conf
source=~/.config/mango/overview.conf

bind=SUPER,r,reload_config


# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:tile
tagrule=id:2,layout_name:tile
tagrule=id:3,layout_name:tile
tagrule=id:4,layout_name:tile
tagrule=id:5,layout_name:tile
tagrule=id:6,layout_name:tile
tagrule=id:7,layout_name:tile
tagrule=id:8,layout_name:tile
tagrule=id:9,layout_name:tile


