# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# terminal
bind=SUPER,Return,spawn,ghostty

# Kill focused program
bind=SUPER,q,killclient,


# switch window focus
bind=SUPER,Tab,focusstack,next # only here because its a default option

# standard arrowkeys controls
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
# toggleglobal bind removed due to not having a use for it
bind=SUPER,Space,togglefloating,
bind=ALT,a,togglemaximizescreen,
bind=SUPER,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# tag switch
bind=SUPER,Left,viewtoleft,0
bind=CTRL,Left,viewtoleft_have_client,0
bind=SUPER,Right,viewtoright,0
bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0


# Switching via SUPER + Number
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0


# move client between work spaces
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0


# tagsilent: move client to the tag and not focus it
bind=SUPER+ALT,1,tagsilent,1,0
bind=SUPER+ALT,2,tagsilent,2,0
bind=SUPER+ALT,3,tagsilent,3,0
bind=SUPER+ALT,4,tagsilent,4,0
bind=SUPER+ALT,5,tagsilent,5,0
bind=SUPER+ALT,6,tagsilent,6,0
bind=SUPER+ALT,7,tagsilent,7,0
bind=SUPER+ALT,8,tagsilent,8,0
bind=SUPER+ALT,9,tagsilent,9,0


# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right
bind=SUPER+Alt,Left,tagmon,left
bind=SUPER+Alt,Right,tagmon,right


# resizewin
bind=CTRL+ALT,Up,resizewin,+0,-50
bind=CTRL+ALT,Down,resizewin,+0,+50
bind=CTRL+ALT,Left,resizewin,-50,+0
bind=CTRL+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
#mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
#mousebind=SUPER,btn_right,moveresize,curresize


# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client