# DISPLAYS
#monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:0,y:10 # Latitute
monitorrule=name:eDP-1,width:1920,height:1080,refresh:144,x:0,y:0 # GF65
#monitorrule=name:eDP-1,width:2560,height:1440,,scale:1.5,refresh:60,x:0,y:10 # XPS-15-9550
#monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:144,x:1920,y:10
#monitorrule=name:HDMI-A-1,width:1920,height:1080,refresh:144,x:0,y:0

allow_tearing=2
syncobj_enable=1
