# overview bind
bind=SUPER,0,toggleoverview,1

# Hot area disable
hotarea_size=0 # double disables
enable_hotarea=0 # disables hot area
hotarea_corner=0 # triple disables
overviewgappi=0 # inner gaps
overviewgappo=0 # outer gaps