# Execute Noctalia shell daemon
exec-once=noctalia-shell -d

# note to self, which noctalia shell crashes you lose everything related to the shell
# i.e: Launcher, Lock screen, Wallpaper, Volume/brightness control


# Binds related to Interacting with the shell
bind=SUPER,D,spawn,noctalia-shell ipc call launcher toggle
bind=SUPER,V,spawn,noctalia-shell ipc call launcher clipboard
bind=SUPER,L,spawn,noctalia-shell ipc call sessionMenu lock
bind =SUPER+SHIFT,X,spawn,noctalia-shell ipc call sessionMenu toggle
bind=SUPER+SHIFT,P,spawn,noctalia-shell ipc call powerProfile cycle
bind=SUPER+SHIFT,W,spawn,noctalia-shell ipc call wallpaper toggle
bindl=NONE,XF86AudioRaiseVolume,spawn,noctalia-shell ipc call volume increase
bindl=NONE,XF86AudioLowerVolume,spawn,noctalia-shell ipc call volume decrease
bindl=NONE,XF86AudioMute,spawn,noctalia-shell ipc call volume muteOutput
bindl=NONE,XF86MonBrightnessUp,spawn,noctalia-shell ipc call brightness increase
bindl=NONE,XF86MonBrightnessDown,spawn,noctalia-shell ipc call brightness decrease